# Setup
title:        Matplotlib for Football
tagline:      A gallery of football plots created using Matplotlib
baseurl:      "/mpl-footy"
paginate:     1
locale:       "en"
category_tags: ["basic"] ##advanced

# About/contact
author:
  name:       Abhishek Sharma
  url:        http://sharmaabhishekk.github.io/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown